const r=require('express').Router();const ah=require('../utils/asyncHandler');const {ok}=require('../utils/respond');const {requireAuth,allowRoles}=require('../middleware/auth');const svc=require('../services/paymentService');const {Payment}=require('../models');
r.post(['/payments/create-order','/payment/create-order','/razorpay/create-order','/payments/razorpay/create-order','/checkout/razorpay/create-order','/checkout/payment/create-order'],requireAuth,allowRoles('CUSTOMER'),ah(async(req,res)=>ok(res,await svc.createOrder({orderId:req.body.orderId||req.body.appOrderId,userId:req.user.id,idempotencyKey:req.headers['idempotency-key']}),'Payment order created')));
r.post(['/payments/verify','/payment/verify','/razorpay/verify','/payments/razorpay/verify','/checkout/razorpay/verify','/checkout/payment/verify'],requireAuth,allowRoles('CUSTOMER'),ah(async(req,res)=>ok(res,await svc.verify(req.body,req.user),'Payment verified')));
r.post(['/payments/failed','/razorpay/failed','/checkout/payment/failed'],requireAuth,allowRoles('CUSTOMER'),ah(async(req,res)=>ok(res,await svc.markFailed(req.body,req.user),'Payment failure recorded')));
r.get('/user/payments',requireAuth,allowRoles('CUSTOMER'),ah(async(req,res)=>{
  const rows=await Payment.find({customerId:req.user.id}).populate('orderId customerId outletId').sort({createdAt:-1}).lean();
  ok(res,rows.map(paymentView));
}));
function paymentView(p){const o=p.orderId||{},u=p.customerId||{},out=p.outletId||{};return {id:String(p._id),gateway:p.gateway||'RAZORPAY',status:p.status,amount:p.amount,currency:p.currency,createdAt:p.createdAt,paidAt:p.updatedAt,razorpayOrderId:p.gatewayOrderId,razorpayPaymentId:p.gatewayPaymentId,orderId:o._id?String(o._id):String(p.orderId||''),orderNumber:o.slug||'',orderSlug:o.slug||'',customerName:u.name||o.address?.name||'',customerPhone:u.phone||o.address?.phone||'',customerEmail:u.email||'',restaurantName:out.name||'',outletName:out.name||'',outletId:out._id?String(out._id):String(p.outletId||''),sellerId:out.sellerId||'',items:o.items||[],subtotal:o.subtotal||0,tax:o.tax||0,deliveryCharge:o.deliveryCharge||0,discount:o.discount||0,total:o.total||p.amount,paymentStatus:o.paymentStatus||p.status,fulfilmentType:o.fulfilmentType||'DELIVERY',failureReason:p.failureReason||'',receiptUrl:`/user/payments/${p._id}/receipt.pdf`};}
module.exports=r;
