const r=require('express').Router();
const PRESET_OUTLET_LOGO='https://res.cloudinary.com/dswsz53xi/image/upload/v1781831035/mr-breado/brands/qogzsdj39ywandrw1g9f.png';const ah=require('../utils/asyncHandler');const {ok}=require('../utils/respond');const {Category,Brand,Banner,BiteStory,Offer,Coupon,Product,Outlet,OutletProduct}=require('../models');const deliveryService=require('../services/deliveryService');const settings=require('../services/settingsService');const {serializeVariantFields}=require('../utils/productVariants');
const active={active:true};
const imageUrl=v=>{if(!v)return'';if(typeof v==='string'){let u=v.trim();if(u.startsWith('//'))u=`https:${u}`;if(u.startsWith('http://res.cloudinary.com/'))u=u.replace('http://','https://');if(u.includes('res.cloudinary.com/')&&u.includes('/upload/')){u=u.replace(/f_auto/g,'f_jpg');if(!u.includes('/upload/f_jpg')&&!u.includes('/upload/q_auto,f_jpg'))u=u.replace('/upload/','/upload/q_auto,f_jpg/');}return u;}if(Array.isArray(v))return imageUrl(v[0]);return imageUrl(v.secure_url||v.secureUrl||v.url||v.src||v.path||v.image||v.imageUrl);};
const categoryOut=c=>({...c,id:String(c._id),categoryId:String(c._id),title:c.name,image:imageUrl(c.image),imageUrl:imageUrl(c.image),icon:imageUrl(c.image),status:c.active?'ACTIVE':'INACTIVE'});
const bannerOut=b=>({...b,id:String(b._id),image:imageUrl(b.image),imageUrl:imageUrl(b.image),banner:imageUrl(b.image),couponCode:b.actionType==='COUPON'?b.actionValue:undefined});
const storyOut=s=>{const media=imageUrl(s.media??s.mediaUrl??s.thumbnailUrl??s.image);return({...s,id:String(s._id),mediaUrl:media,media_url:media,thumbnailUrl:media,thumbnail_url:media,image:media,imageUrl:media,active:s.active!==false});};
const offerOut=o=>{const image=imageUrl(o.image??o.banner??o.imageUrl??o.image_url);const code=String(o.code??o.couponCode??'').trim().toUpperCase();const type=String(o.type??o.discountType??'').trim().toUpperCase();return({...o,id:String(o._id),image,imageUrl:image,image_url:image,banner:image,bannerImage:image,couponCode:code,coupon_code:code,code,discountType:type,discount_type:type,discountValue:Number(o.value??o.discountValue??0),discount_value:Number(o.value??o.discountValue??0),activeNow:o.active!==false});};
const addressText=a=>{if(typeof a==='string')return a;return[a?.line1,a?.line2,a?.area,a?.landmark,a?.city,a?.state,a?.pincode].filter(Boolean).join(', ');};
const outletOut=o=>{const logo=PRESET_OUTLET_LOGO,banner=imageUrl(o.coverImage??o.cover_image??o.bannerImage??o.banner),address=addressText(o.address);return({...o,id:String(o._id),outletId:String(o._id),restaurantId:String(o._id),outletName:o.name,restaurantName:o.name,address,addressText:address,fullAddress:address,city:o.address?.city||'',state:o.address?.state||'',pincode:o.address?.pincode||'',deliveryRadiusKm:Number(o.deliveryRadiusKm||0),serviceRadiusKm:Number(o.deliveryRadiusKm||0),radiusKm:Number(o.deliveryRadiusKm||0),latitude:o.location?.coordinates?.[1]??0,longitude:o.location?.coordinates?.[0]??0,logo:logo,logoImage:logo,profileImage:logo,image:banner||logo,imageUrl:banner||logo,banner,bannerImage:banner,coverImage:banner});};
const productOut=(p,row)=>{const img=imageUrl(p.images);const availableStock=Math.max(0,Number(row.stockQuantity||0)-Number(row.reservedQuantity||0));const price=Number(p.offerPrice>0?p.offerPrice:p.basePrice);return{...p,...serializeVariantFields(p),id:String(p._id),productId:String(p._id),title:p.name,image:img,imageUrl:img,thumbnail:img,categoryName:p.categoryId?.name||'',brandId:p.brandId?._id?String(p.brandId._id):(p.brandId?String(p.brandId):''),brandName:p.brandId?.name||'',brandSlug:p.brandId?.slug||'',brand:p.brandId||null,foodType:p.foodType,isVeg:p.foodType==='VEG',veg:p.foodType==='VEG',outletProductId:String(row._id),outletId:String(row.outletId?._id||row.outletId),stockQuantity:Number(row.stockQuantity||0),reservedQuantity:Number(row.reservedQuantity||0),availableStock,inStock:availableStock>0,isAvailable:availableStock>0,available:availableStock>0,price:Number(row.priceOverride??price),effectivePrice:Number(row.offerPriceOverride??row.priceOverride??price),preparationMinutes:row.preparationMinutes};};
r.get(['/settings','/payment/settings','/payments/settings','/payment/options','/app/settings','/public/settings'],ah(async(req,res)=>{const f=await settings.getBusinessFeatures();const pub=await settings.publicSettings();ok(res,{...pub,razorpayConfigured:Boolean(pub.payment?.onlinePaymentConfigured),onlinePaymentConfigured:Boolean(pub.payment?.onlinePaymentConfigured),razorpayKeyId:pub.razorpayKeyId||pub.payment?.razorpayKeyId||'',onlinePaymentEnabled:f.feature_toggles.onlinePayment,codEnabled:f.feature_toggles.cod,takeawayEnabled:f.feature_toggles.takeaway,mrBreadoTakeawayEnabled:f.feature_toggles.takeaway,deliveryEnabled:f.feature_toggles.delivery,offersEnabled:f.feature_toggles.offers,takeawayAdvancePercentage:f.takeaway.advanceValue,featureToggles:f.feature_toggles,feature_toggles:f.feature_toggles,takeaway:f.takeaway});}));
r.get(['/categories','/food-categories'],ah(async(req,res)=>ok(res,(await Category.find(active).sort({sortOrder:1,name:1}).lean()).map(categoryOut))));
r.get('/categories/sub-categories',ah(async(req,res)=>ok(res,(await Category.find({active:true,parentId:{$ne:null}}).lean()).map(categoryOut))));
r.get('/brands',ah(async(req,res)=>ok(res,(await Brand.find(active).lean()).map(x=>({...x,image:imageUrl(x.image),imageUrl:imageUrl(x.image)})))));
r.get('/banners',ah(async(req,res)=>ok(res,(await Banner.find(active).sort({sortOrder:1}).lean()).map(bannerOut))));
r.get('/stories',ah(async(req,res)=>{const now=new Date();const rows=await BiteStory.find({active:true,$and:[{$or:[{startsAt:null},{startsAt:{$exists:false}},{startsAt:{$lte:now}}]},{$or:[{endsAt:null},{endsAt:{$exists:false}},{endsAt:{$gte:now}}]}]}).sort({sortOrder:1,createdAt:-1}).lean();ok(res,rows.map(storyOut));}));
r.get('/offers',ah(async(req,res)=>{const now=new Date();const dateFilter={$and:[{$or:[{startAt:null},{startAt:{$exists:false}},{startAt:{$lte:now}}]},{$or:[{endAt:null},{endAt:{$exists:false}},{endAt:{$gte:now}}]}]};const outletId=req.query.outletId||req.query.outlet_id||req.query.restaurantId;const scope=outletId?{$or:[{outletIds:{$exists:false}},{outletIds:{$size:0}},{outletIds:outletId}]}:{};const [offers,coupons]=await Promise.all([Offer.find({active:true,...dateFilter,...scope}).lean(),Coupon.find({active:true,...dateFilter,...scope}).lean()]);const couponByCode=new Map(coupons.map(c=>[String(c.code||'').trim().toUpperCase(),c]));const rows=offers.map(o=>{const x=offerOut(o),c=x.code?couponByCode.get(x.code):null;return{...x,hasValidCoupon:Boolean(c),exploreEnabled:Boolean(c),coupon:c?offerOut(c):null,outletIds:(o.outletIds||[]).map(String),appliesToAllOutlets:!(o.outletIds||[]).length};});ok(res,rows); }));
r.get('/products',ah(async(req,res)=>{const q={active:true};if(req.query.categoryId)q.categoryId=req.query.categoryId;if(req.query.category)q.categoryId=req.query.category;if(req.query.search)q.name={$regex:String(req.query.search),$options:'i'};if(req.query.brandId)q.brandId=req.query.brandId;if(req.query.brand||req.query.brandSlug){const b=await Brand.findOne({slug:String(req.query.brand||req.query.brandSlug).toLowerCase(),active:true}).lean();if(!b)return ok(res,[]);q.brandId=b._id;}const products=await Product.find(q).populate('categoryId brandId').limit(Math.min(100,Number(req.query.limit||30))).lean();ok(res,products.map(p=>{const img=imageUrl(p.images);return{...p,...serializeVariantFields(p),id:String(p._id),productId:String(p._id),title:p.name,image:img,imageUrl:img,foodType:p.foodType,isVeg:p.foodType==='VEG',categoryName:p.categoryId?.name||'',price:p.offerPrice>0?p.offerPrice:p.basePrice};}));}));
r.get('/products/:slug',ah(async(req,res)=>{const p=await Product.findOne({slug:req.params.slug,active:true}).populate('categoryId brandId').lean();if(!p)return ok(res,null);const img=imageUrl(p.images);ok(res,{...p,...serializeVariantFields(p),id:String(p._id),productId:String(p._id),title:p.name,image:img,imageUrl:img,foodType:p.foodType,isVeg:p.foodType==='VEG',categoryName:p.categoryId?.name||'',price:p.offerPrice>0?p.offerPrice:p.basePrice});}));
r.get(['/restaurants','/outlets'],ah(async(req,res)=>{const rows=await Outlet.find({active:true,open:true}).lean();const lat=Number(req.query.latitude??req.query.lat),lng=Number(req.query.longitude??req.query.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return ok(res,rows.map(outletOut));const road=await deliveryService.googleRoadDistances({latitude:lat,longitude:lng},rows).catch(()=>new Map());const data=rows.map(o=>{const route=road.get(String(o._id));return outletOut({...o,distanceKm:route?.distanceKm,exactDistanceKm:route?.distanceKm,estimatedTravelMinutes:route?.durationMinutes,serviceable:route?.distanceKm!=null&&route.distanceKm<=Number(o.deliveryRadiusKm||0)});}).sort((a,b)=>(a.distanceKm??Number.MAX_SAFE_INTEGER)-(b.distanceKm??Number.MAX_SAFE_INTEGER));ok(res,data); }));
r.get(['/restaurants/nearby','/outlets/nearby'],ah(async(req,res)=>{const lat=Number(req.query.latitude||req.query.lat),lng=Number(req.query.longitude||req.query.lng);const rows=Number.isFinite(lat)&&Number.isFinite(lng)?await Outlet.aggregate([{$geoNear:{near:{type:'Point',coordinates:[lng,lat]},distanceField:'distanceMeters',spherical:true,query:{active:true,open:true}}},{$addFields:{distanceKm:{$divide:['$distanceMeters',1000]}}},{$match:{$expr:{$lte:['$distanceKm','$deliveryRadiusKm']}}},{$limit:50}]):await Outlet.find({active:true,open:true}).lean();ok(res,rows.map(outletOut));}));
r.get(['/restaurants/:slug','/stores/:slug'],ah(async(req,res)=>{const o=await Outlet.findOne({slug:req.params.slug,active:true}).lean();ok(res,o?outletOut(o):null);}));
async function menu(outletId,query={}){const rows=await OutletProduct.find({outletId,enabled:true}).populate({path:'productId',match:{active:true},populate:[{path:'categoryId'},{path:'brandId'}]}).populate('outletId').lean();return rows.filter(x=>x.productId).filter(x=>!query.categoryId||String(x.productId.categoryId?._id||x.productId.categoryId)===String(query.categoryId)).filter(x=>!query.search||x.productId.name.toLowerCase().includes(String(query.search).toLowerCase())).filter(x=>!query.brandId||String(x.productId.brandId?._id||x.productId.brandId)===String(query.brandId)).filter(x=>!query.brand&&!query.brandSlug||String(x.productId.brandId?.slug||'').toLowerCase()===String(query.brand||query.brandSlug).toLowerCase()).map(x=>productOut(x.productId,x));}
r.get(['/outlets/:id/menu','/user/outlets/:id/menu','/outlets/:id/foods/search','/user/outlets/:id/foods/search'],ah(async(req,res)=>ok(res,await menu(req.params.id,req.query))));
r.get(['/stores/:slug/menu','/restaurants/:slug/menu'],ah(async(req,res)=>{const o=await Outlet.findOne({slug:req.params.slug,active:true});ok(res,o?await menu(o._id,req.query):[]);}));
r.get('/home',ah(async(req,res)=>{
  const now=new Date();const dateFilter={$and:[{$or:[{startAt:null},{startAt:{$exists:false}},{startAt:{$lte:now}}]},{$or:[{endAt:null},{endAt:{$exists:false}},{endAt:{$gte:now}}]}]};
  const [banners,categories,brands,offers,coupons,stories]=await Promise.all([Banner.find(active).sort({sortOrder:1}).lean(),Category.find(active).sort({sortOrder:1}).lean(),Brand.find(active).sort({name:1}).lean(),Offer.find({active:true,...dateFilter}).lean(),Coupon.find({active:true,...dateFilter}).lean(),BiteStory.find({active:true,...dateFilter}).sort({sortOrder:1,createdAt:-1}).lean()]);
  const lat=Number(req.query.latitude||req.query.userLat||req.query.user_latitude),lng=Number(req.query.longitude||req.query.userLng||req.query.user_longitude);
  let outlets=[];let nearestOutlet=null;let serviceability=null;let products=[];
  if(Number.isFinite(lat)&&Number.isFinite(lng)){
    serviceability=await deliveryService.checkServiceability({latitude:lat,longitude:lng});
    if(serviceability.serviceable){
      const outlet=await Outlet.findById(serviceability.nearestOutletId).lean();if(outlet){nearestOutlet={...outletOut(outlet),distanceKm:serviceability.distanceKm,estimatedTravelMinutes:serviceability.estimatedTravelMinutes};outlets=[nearestOutlet];products=await menu(outlet._id,{});}
    }
  } else outlets=(await Outlet.find({active:true,open:true}).limit(10).lean()).map(outletOut);
  const selectedOutletId=nearestOutlet?.id||null;const inScope=(x)=>!(x.outletIds||[]).length||!selectedOutletId||(x.outletIds||[]).some(id=>String(id)===String(selectedOutletId));const validCoupons=coupons.filter(inScope);const couponByCode=new Map(validCoupons.map(c=>[String(c.code||'').trim().toUpperCase(),c]));const promotions=offers.filter(inScope).map(o=>{const x=offerOut(o),c=x.code?couponByCode.get(x.code):null;return {...x,hasValidCoupon:Boolean(c),exploreEnabled:Boolean(c),coupon:c?offerOut(c):null,outletIds:(o.outletIds||[]).map(String),appliesToAllOutlets:!(o.outletIds||[]).length};});
  ok(res,{stories:stories.map(storyOut),banners:banners.map(bannerOut),categories:categories.map(categoryOut),brands:brands.map(b=>({...b,id:String(b._id),image:imageUrl(b.image),imageUrl:imageUrl(b.image),logo:imageUrl(b.image)})),offers:promotions,coupons:validCoupons.map(offerOut),outlets,restaurants:outlets,nearestOutlet,products,featuredFoods:products,popularFoods:products,serviceability,noOutletAvailable:Boolean(serviceability&&!serviceability.serviceable),message:serviceability?.message||''});
}));
module.exports=r;
