const r=require('express').Router();const mongoose=require('mongoose');const ah=require('../utils/asyncHandler');const {ok}=require('../utils/respond');const {requireAuth,allowRoles}=require('../middleware/auth');const {Order,OutletProduct,OfflineSale,InventoryMovement,DailyClosing,Outlet}=require('../models');const {AppError}=require('../utils/errors');
r.use(['/seller','/outlet-manager'],requireAuth,allowRoles('SELLER','ADMIN'));
const allowed=(u,id)=>u.role==='ADMIN'||(u.assignedOutletIds||[]).map(String).includes(String(id));
r.get(['/seller/restaurant','/outlet-manager/outlet'],ah(async(req,res)=>ok(res,await Outlet.find({_id:{$in:req.user.assignedOutletIds||[]}}).lean())));
r.get(['/seller/orders','/outlet-manager/orders'],ah(async(req,res)=>{const ids=req.user.role==='ADMIN'?(req.query.outletId?[req.query.outletId]:await Outlet.distinct('_id')):req.user.assignedOutletIds;ok(res,await Order.find({outletId:{$in:ids}}).populate('customerId riderId outletId').sort({createdAt:-1}).lean())}));
r.get(['/seller/products','/outlet-manager/products'],ah(async(req,res)=>{const id=req.query.outletId||req.user.assignedOutletIds?.[0];if(!allowed(req.user,id))throw new AppError('Outlet access denied',403);ok(res,await OutletProduct.find({outletId:id}).populate('productId').lean())}));
r.post(['/seller/offline-sales','/outlet-manager/offline-sales'],ah(async(req,res)=>{const outletId=req.body.outletId||req.user.assignedOutletIds?.[0];if(!allowed(req.user,outletId))throw new AppError('Outlet access denied',403);const key=req.headers['idempotency-key']||req.body.idempotencyKey;if(!key)throw new AppError('Idempotency-Key is required');const old=await OfflineSale.findOne({idempotencyKey:key});if(old)return ok(res,old,'Offline sale already processed');const session=await mongoose.startSession();let sale;await session.withTransaction(async()=>{let subtotal=0;const items=[];for(const item of req.body.items||[]){const row=await OutletProduct.findOne({outletId,productId:item.productId}).populate('productId').session(session);if(!row||row.stockQuantity<Number(item.quantity))throw new AppError('Insufficient stock',409);const before=row.stockQuantity;const price=Number(item.unitPrice??row.priceOverride??row.productId.offerPrice??row.productId.basePrice);row.stockQuantity-=Number(item.quantity);await row.save({session});items.push({productId:row.productId._id,name:row.productId.name,quantity:Number(item.quantity),unitPrice:price,total:price*Number(item.quantity)});subtotal+=price*Number(item.quantity);await InventoryMovement.create([{outletId,productId:row.productId._id,type:'OFFLINE_SALE',quantityBefore:before,quantityChanged:-Number(item.quantity),quantityAfter:row.stockQuantity,reservedBefore:row.reservedQuantity,reservedAfter:row.reservedQuantity,referenceType:'OFFLINE_SALE',reason:'Seller offline sale',performedBy:req.user.id,idempotencyKey:`${key}:${row.productId._id}`}],{session});}[sale]=await OfflineSale.create([{outletId,sellerId:req.user.id,items,subtotal,tax:Number(req.body.tax||0),total:subtotal+Number(req.body.tax||0),paymentMode:req.body.paymentMode||'CASH',idempotencyKey:key}],{session});});await session.endSession();ok(res,sale,'Offline sale recorded',201)}));
r.post(['/seller/day-close','/outlet-manager/day-close','/seller/end-of-day'],ah(async(req,res)=>{const outletId=req.body.outletId||req.user.assignedOutletIds?.[0];if(!allowed(req.user,outletId))throw new AppError('Outlet access denied',403);const businessDate=req.body.businessDate||new Date().toISOString().slice(0,10);const inventory=await OutletProduct.find({outletId}).lean();const start=new Date(`${businessDate}T00:00:00.000Z`),end=new Date(`${businessDate}T23:59:59.999Z`);const [orders,offline]=await Promise.all([Order.find({outletId,status:'DELIVERED',deliveredAt:{$gte:start,$lte:end}}).lean(),OfflineSale.find({outletId,createdAt:{$gte:start,$lte:end}}).lean()]);const closing=await DailyClosing.findOneAndUpdate({outletId,businessDate},{$set:{sellerId:req.user.id,stockSnapshot:inventory.map(x=>({productId:x.productId,stockQuantity:x.stockQuantity,reservedQuantity:x.reservedQuantity})),onlineSales:orders.reduce((a,x)=>a+x.total,0),offlineSales:offline.reduce((a,x)=>a+x.total,0),totalSales:orders.reduce((a,x)=>a+x.total,0)+offline.reduce((a,x)=>a+x.total,0),notes:req.body.notes,submittedAt:new Date()}},{upsert:true,new:true});ok(res,closing,'Day closing submitted')}));
module.exports=r;
