const crypto=require('crypto');
const Razorpay=require('razorpay');
const mongoose=require('mongoose');
const {Order,Payment}=require('../models');
const settings=require('./settingsService');
const {AppError}=require('../utils/errors');

async function client(){const cfg=await settings.getRazorpayConfig();if(!cfg.keyId||!cfg.keySecret)throw new AppError('Online payment is not configured',503,'PAYMENT_NOT_CONFIGURED');return {instance:new Razorpay({key_id:cfg.keyId,key_secret:cfg.keySecret}),cfg};}
async function createOrder({orderId,userId,idempotencyKey}){const order=await Order.findOne({_id:orderId,customerId:userId});if(!order)throw new AppError('Order not found',404);const features=await settings.getBusinessFeatures();if(!features.feature_toggles.onlinePayment)throw new AppError('Online payment is currently disabled',409,'ONLINE_PAYMENT_DISABLED');if(order.fulfilmentType==='TAKEAWAY'&&!features.feature_toggles.takeaway)throw new AppError('Takeaway is currently disabled',409,'TAKEAWAY_DISABLED');const amount=Number(order.payableOnlineAmount||order.total||0);if(amount<=0)throw new AppError('No online amount is payable for this order',409,'NO_ONLINE_AMOUNT_DUE');const {instance,cfg}=await client();const old=await Payment.findOne({orderId:order._id});if(old?.gatewayOrderId)return{keyId:cfg.keyId,razorpayOrderId:old.gatewayOrderId,amount:Math.round(old.amount*100),currency:old.currency,appOrderId:String(order._id),fullOrderTotal:order.total,balanceDue:order.balanceDue||0,takeawayAdvancePercentage:order.takeawayAdvancePercentage||0};const rz=await instance.orders.create({amount:Math.round(amount*100),currency:'INR',receipt:order.slug,notes:{appOrderId:String(order._id),outletId:String(order.outletId),customerId:String(userId),fulfilmentType:order.fulfilmentType,fullOrderTotal:String(order.total)}});await Payment.create({orderId:order._id,customerId:userId,outletId:order.outletId,gatewayOrderId:rz.id,amount,currency:'INR',tax:order.tax,status:'PENDING',idempotencyKey:idempotencyKey||`payment:${order._id}`});return{keyId:cfg.keyId,razorpayOrderId:rz.id,amount:rz.amount,currency:rz.currency,appOrderId:String(order._id),fullOrderTotal:order.total,balanceDue:order.balanceDue||0,takeawayAdvancePercentage:order.takeawayAdvancePercentage||0};}
async function verify(body,user){const {razorpay_order_id,razorpay_payment_id,razorpay_signature}=body;const p=await Payment.findOne({gatewayOrderId:razorpay_order_id,customerId:user.id});if(!p)throw new AppError('Payment transaction not found',404);if(p.status==='SUCCESS')return p;const cfg=await settings.getRazorpayConfig();const expected=crypto.createHmac('sha256',cfg.keySecret).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest('hex');const supplied=String(razorpay_signature||'');if(expected.length!==supplied.length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(supplied)))throw new AppError('Invalid payment signature',400,'INVALID_SIGNATURE');const session=await mongoose.startSession();try{await session.withTransaction(async()=>{p.gatewayPaymentId=razorpay_payment_id;p.signature=razorpay_signature;p.status='SUCCESS';await p.save({session});const order=await Order.findById(p.orderId).session(session);if(!order)throw new AppError('Order not found',404);const paidAmount=Number(p.amount||0);const balanceDue=Math.max(0,Number((Number(order.total||0)-paidAmount).toFixed(2)));await Order.updateOne({_id:p.orderId},{$set:{paymentStatus:balanceDue>0?'PARTIALLY_PAID':'SUCCESS',paidAmount,balanceDue,status:'RECEIVED'}},{session});});}finally{await session.endSession();}return p;}
async function webhook(raw,signature,eventId){const cfg=await settings.getRazorpayConfig(false);if(!cfg.webhookSecret)throw new AppError('Webhook secret not configured',503);const expected=crypto.createHmac('sha256',cfg.webhookSecret).update(raw).digest('hex');const supplied=String(signature||'');if(expected.length!==supplied.length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(supplied)))throw new AppError('Invalid webhook signature',400);const event=JSON.parse(raw.toString('utf8'));const entity=event.payload?.payment?.entity;if(entity?.id)await Payment.updateOne({$or:[{gatewayPaymentId:entity.id},{gatewayOrderId:entity.order_id}]},{$set:{gatewayPaymentId:entity.id,rawMetadata:{event:event.event,eventId}}});return{event:event.event,eventId};}
module.exports={createOrder,verify,webhook};
