const mongoose = require('mongoose');
const { Schema, model, models } = mongoose;
const objectId = (ref, required=false) => ({ type: Schema.Types.ObjectId, ref, required, index: true });
const money = { type: Number, min: 0, default: 0 };
const imageSchema = new Schema({ url:String, publicId:String, alt:String }, { _id:false });
const addressSchema = new Schema({ label:String, line1:String, line2:String, area:String, city:String, state:String, pincode:String, landmark:String, latitude:Number, longitude:Number, isDefault:{type:Boolean,default:false} }, { timestamps:true });

const User = models.User || model('User', new Schema({
  name:{type:String,required:true,trim:true}, email:{type:String,trim:true,lowercase:true,sparse:true,unique:true}, phone:{type:String,trim:true,sparse:true,unique:true}, passwordHash:{type:String,required:true,select:false}, role:{type:String,enum:['ADMIN','SELLER','RIDER','CUSTOMER'],default:'CUSTOMER',index:true}, active:{type:Boolean,default:true}, avatar:imageSchema, assignedOutletIds:[objectId('Outlet')], addresses:[addressSchema], favoriteProductIds:[objectId('Product')], walletBalance:{type:Number,default:0,min:0}, rewardPoints:{type:Number,default:0,min:0}, fcmTokens:[String], lastLoginAt:Date
},{timestamps:true}));

const Outlet = models.Outlet || model('Outlet', new Schema({
  name:{type:String,required:true,trim:true}, slug:{type:String,required:true,unique:true,index:true}, code:{type:String,unique:true,sparse:true}, logo:imageSchema, coverImage:imageSchema, gstin:String, businessRegistration:String, managerName:String, managerPhone:String, email:String, address:{line1:String,line2:String,area:String,city:String,state:String,pincode:String,landmark:String}, location:{type:{type:String,enum:['Point'],default:'Point'},coordinates:{type:[Number],default:[0,0]}}, deliveryRadiusKm:{type:Number,default:10,min:0}, operatingHours:{type:Schema.Types.Mixed,default:{}}, active:{type:Boolean,default:true,index:true}, open:{type:Boolean,default:true,index:true}, primary:{type:Boolean,default:false,index:true}, rating:{type:Number,default:0}, ratingCount:{type:Number,default:0}, deliverySettings:{baseCharge:{type:Number,default:0},perKmCharge:{type:Number,default:0},minimumCharge:{type:Number,default:0},maximumCharge:{type:Number,default:9999}}, createdBy:objectId('User')
},{timestamps:true}));
Outlet.schema.index({location:'2dsphere'});

const Category = models.Category || model('Category', new Schema({ name:{type:String,required:true,trim:true}, slug:{type:String,required:true,unique:true,index:true}, image:imageSchema, description:String, active:{type:Boolean,default:true,index:true}, parentId:objectId('Category'), sortOrder:{type:Number,default:0} },{timestamps:true}));
const Brand = models.Brand || model('Brand', new Schema({name:{type:String,required:true},slug:{type:String,required:true,unique:true},image:imageSchema,active:{type:Boolean,default:true}}, {timestamps:true}));
const Product = models.Product || model('Product', new Schema({
  name:{type:String,required:true,trim:true}, slug:{type:String,required:true,unique:true,index:true}, sku:{type:String,unique:true,sparse:true,index:true}, description:String, images:[imageSchema], categoryId:objectId('Category'), subcategoryId:objectId('Category'), brandId:objectId('Brand'), basePrice:money, offerPrice:money, ingredients:[String], nutritionalInfo:Schema.Types.Mixed, active:{type:Boolean,default:true,index:true}, featured:{type:Boolean,default:false}, foodType:{type:String,enum:['VEG','NON_VEG','EGG','VEGAN','OTHER'],default:'OTHER'}, customizationGroups:[{name:String,type:{type:String,enum:['SINGLE','MULTIPLE']},required:Boolean,minSelect:Number,maxSelect:Number,options:[{name:String,price:Number,active:{type:Boolean,default:true}}]}], createdBy:objectId('User')
},{timestamps:true}));

const OutletProduct = models.OutletProduct || model('OutletProduct', new Schema({
  outletId:objectId('Outlet',true), productId:objectId('Product',true), enabled:{type:Boolean,default:true,index:true}, available:{type:Boolean,default:true,index:true}, stockQuantity:{type:Number,default:0,min:0}, reservedQuantity:{type:Number,default:0,min:0}, lowStockThreshold:{type:Number,default:5,min:0}, priceOverride:{type:Number,min:0}, offerPriceOverride:{type:Number,min:0}, costPrice:{type:Number,min:0}, preparationMinutes:{type:Number,default:20,min:0}, version:{type:Number,default:0}
},{timestamps:true}));
OutletProduct.schema.index({outletId:1,productId:1},{unique:true});

const Cart = models.Cart || model('Cart', new Schema({ customerId:objectId('User',true), outletId:objectId('Outlet',true), items:[{productId:objectId('Product',true),quantity:{type:Number,min:1,required:true},customizations:[{groupName:String,optionName:String,price:Number}]}], couponCode:String },{timestamps:true}));
Cart.schema.index({customerId:1,outletId:1},{unique:true});

const orderItemSchema = new Schema({ productId:objectId('Product'), name:String, slug:String, sku:String, image:String, quantity:Number, unitPrice:Number, offerPrice:Number, tax:Number, customizations:[Schema.Types.Mixed], finalTotal:Number },{_id:true});
const Order = models.Order || model('Order', new Schema({
  slug:{type:String,required:true,unique:true,index:true}, clientRequestId:{type:String,sparse:true,unique:true}, customerId:objectId('User',true), outletId:objectId('Outlet',true), sellerId:objectId('User'), riderId:objectId('User'), items:[orderItemSchema], address:addressSchema, fulfilmentType:{type:String,enum:['DELIVERY','TAKEAWAY'],default:'DELIVERY',index:true}, status:{type:String,default:'RECEIVED',index:true}, paymentMethod:{type:String,enum:['COD','ONLINE','WALLET','TAKEAWAY_ADVANCE'],default:'COD'}, paymentStatus:{type:String,default:'PENDING',index:true}, subtotal:Number,discount:Number,tax:Number,deliveryCharge:Number,total:Number,payableOnlineAmount:Number,paidAmount:{type:Number,default:0},balanceDue:{type:Number,default:0},takeawayAdvancePercentage:Number,distanceKm:Number,cancellationReason:String,refundStatus:String,invoiceStatus:String, acceptedAt:Date,readyAt:Date,pickedUpAt:Date,deliveredAt:Date,cancelledAt:Date,sellerAcceptanceDeadline:Date,riderAcceptanceDeadline:Date
},{timestamps:true}));
Order.schema.index({outletId:1,status:1,createdAt:-1}); Order.schema.index({customerId:1,createdAt:-1}); Order.schema.index({riderId:1,status:1});

const OrderEvent = models.OrderEvent || model('OrderEvent', new Schema({ orderId:objectId('Order',true), previousStatus:String,newStatus:String,actorType:String,actorId:objectId('User'),reason:String,metadata:Schema.Types.Mixed,idempotencyKey:{type:String,unique:true,sparse:true} },{timestamps:true}));
const InventoryMovement = models.InventoryMovement || model('InventoryMovement', new Schema({ outletId:objectId('Outlet',true),productId:objectId('Product',true),type:String,quantityBefore:Number,quantityChanged:Number,quantityAfter:Number,reservedBefore:Number,reservedAfter:Number,referenceType:String,referenceId:Schema.Types.ObjectId,reason:String,performedBy:objectId('User'),idempotencyKey:{type:String,unique:true} },{timestamps:true}));
const Payment = models.Payment || model('Payment', new Schema({ orderId:objectId('Order'),customerId:objectId('User',true),outletId:objectId('Outlet'),gateway:{type:String,default:'RAZORPAY'},gatewayOrderId:{type:String,sparse:true},gatewayPaymentId:{type:String,sparse:true},signature:String,amount:Number,currency:{type:String,default:'INR'},tax:Number,status:{type:String,default:'PENDING',index:true},failureReason:String,idempotencyKey:{type:String,unique:true,sparse:true},rawMetadata:Schema.Types.Mixed },{timestamps:true}));
Payment.schema.index({gateway:1,gatewayOrderId:1},{unique:true,sparse:true}); Payment.schema.index({gateway:1,gatewayPaymentId:1},{unique:true,sparse:true});
const Refund = models.Refund || model('Refund', new Schema({orderId:objectId('Order',true),paymentId:objectId('Payment',true),customerId:objectId('User',true),outletId:objectId('Outlet',true),amount:Number,cancellationReason:String,gatewayRefundId:String,status:{type:String,default:'PENDING',index:true},adminAcknowledgement:{type:Boolean,default:false},adminNote:String,processedBy:objectId('User'),processedAt:Date},{timestamps:true}));
Refund.schema.index({orderId:1,paymentId:1},{unique:true});
const RiderLocation = models.RiderLocation || model('RiderLocation', new Schema({riderId:objectId('User',true),orderId:objectId('Order'),location:{type:{type:String,default:'Point'},coordinates:[Number]},heading:Number,speed:Number,accuracy:Number,recordedAt:{type:Date,default:Date.now}}, {timestamps:true})); RiderLocation.schema.index({location:'2dsphere'}); RiderLocation.schema.index({riderId:1,recordedAt:-1});
const RiderEarning = models.RiderEarning || model('RiderEarning', new Schema({riderId:objectId('User',true),orderId:{type:Schema.Types.ObjectId,ref:'Order',required:true,unique:true},outletId:objectId('Outlet',true),distanceKm:Number,ratePerKm:Number,amount:Number,status:{type:String,default:'PENDING'},settledAt:Date},{timestamps:true}));
const OfflineSale = models.OfflineSale || model('OfflineSale', new Schema({outletId:objectId('Outlet',true),sellerId:objectId('User',true),items:[{productId:objectId('Product',true),name:String,quantity:Number,unitPrice:Number,total:Number}],subtotal:Number,tax:Number,total:Number,paymentMode:String,idempotencyKey:{type:String,unique:true}},{timestamps:true}));
const Invoice = models.Invoice || model('Invoice', new Schema({orderId:{type:Schema.Types.ObjectId,ref:'Order',required:true,unique:true},invoiceNumber:{type:String,required:true,unique:true},invoiceDate:{type:Date,default:Date.now},pdfUrl:String,generatedAt:{type:Date,default:Date.now}},{timestamps:true}));
const Setting = models.Setting || model('Setting', new Schema({key:{type:String,required:true,unique:true,index:true},value:Schema.Types.Mixed,encryptedValue:String,encryptionIv:String,encryptionTag:String,isSecret:{type:Boolean,default:false,index:true},public:{type:Boolean,default:false},active:{type:Boolean,default:true,index:true},version:{type:Number,default:1},lastValidatedAt:Date,updatedBy:objectId('User')},{timestamps:true}));
const SettingAudit = models.SettingAudit || model('SettingAudit', new Schema({settingKey:{type:String,required:true,index:true},action:{type:String,required:true},changedBy:objectId('User'),previousMasked:Schema.Types.Mixed,nextMasked:Schema.Types.Mixed,requestId:String},{timestamps:true}));
const Notification = models.Notification || model('Notification', new Schema({userId:objectId('User'),outletId:objectId('Outlet'),role:String,title:String,message:String,type:String,data:Schema.Types.Mixed,read:{type:Boolean,default:false,index:true}},{timestamps:true}));
const Banner = models.Banner || model('Banner', new Schema({title:String,subtitle:String,image:imageSchema,actionType:String,actionValue:String,active:{type:Boolean,default:true},sortOrder:Number},{timestamps:true}));
const Offer = models.Offer || model('Offer', new Schema({title:String,code:{type:String,unique:true,sparse:true},description:String,type:String,value:Number,minOrder:Number,maxDiscount:Number,startAt:Date,endAt:Date,active:{type:Boolean,default:true},outletIds:[objectId('Outlet')],productIds:[objectId('Product')]},{timestamps:true}));
const Coupon = models.Coupon || model('Coupon', new Schema({code:{type:String,required:true,unique:true,uppercase:true},type:String,value:Number,minOrder:Number,maxDiscount:Number,usageLimit:Number,usedCount:{type:Number,default:0},startAt:Date,endAt:Date,active:{type:Boolean,default:true}},{timestamps:true}));
const Review = models.Review || model('Review', new Schema({customerId:objectId('User',true),orderId:objectId('Order',true),outletId:objectId('Outlet',true),productId:objectId('Product'),rating:{type:Number,min:1,max:5},comment:String},{timestamps:true})); Review.schema.index({customerId:1,orderId:1},{unique:true});
const WalletTransaction = models.WalletTransaction || model('WalletTransaction', new Schema({userId:objectId('User',true),type:{type:String,enum:['CREDIT','DEBIT']},amount:Number,referenceType:String,referenceId:Schema.Types.ObjectId,description:String,balanceAfter:Number},{timestamps:true}));
const SupportTicket = models.SupportTicket || model('SupportTicket', new Schema({userId:objectId('User',true),subject:String,message:String,status:{type:String,default:'OPEN',index:true},priority:{type:String,default:'NORMAL'},assignedTo:objectId('User'),responses:[{senderId:objectId('User'),message:String,createdAt:{type:Date,default:Date.now}}]},{timestamps:true}));
const VerificationRequest = models.VerificationRequest || model('VerificationRequest', new Schema({userId:objectId('User',true),outletId:objectId('Outlet'),type:String,status:{type:String,default:'PENDING',index:true},documents:[imageSchema],note:String,reviewedBy:objectId('User'),reviewedAt:Date},{timestamps:true}));
const DailyClosing = models.DailyClosing || model('DailyClosing', new Schema({outletId:objectId('Outlet',true),sellerId:objectId('User',true),businessDate:{type:String,required:true},stockSnapshot:[{productId:objectId('Product'),stockQuantity:Number,reservedQuantity:Number}],onlineSales:Number,offlineSales:Number,totalSales:Number,notes:String,submittedAt:{type:Date,default:Date.now}},{timestamps:true})); DailyClosing.schema.index({outletId:1,businessDate:1},{unique:true});

module.exports={User,Outlet,Category,Brand,Product,OutletProduct,Cart,Order,OrderEvent,InventoryMovement,Payment,Refund,RiderLocation,RiderEarning,OfflineSale,Invoice,Setting,SettingAudit,Notification,Banner,Offer,Coupon,Review,WalletTransaction,SupportTicket,VerificationRequest,DailyClosing};
